---
title: "Workshop 2: Advanced data wrangling: Extracting ecological signals from noisy systems"
author: "Celine M. Egsaeter"
format:
  html:
    embed-resources: true
execute:
  warning: false
  message: false
---

#### Housekeeping
```{r}
## Inventory every active object currently residing in session RAM
objects()
## Purge global environment
rm(list = ls())
# Confirm that global session memory now completely vacant
objects()
```

#### Library
```{r}
# Load the primary data science framework
library(tidyverse)
```


# 2.2 Tidying data

1.	Put each dataset in a tibble (special dataframe)

**table 1**
```{r}
#Creating tibble from the data in the workbook
table1 <- tibble(
  country = c("Afghanistan", "Afghanistan", "Brazil", "Brazil", "China", "China"),
  year = c(1999, 2000, 1999, 2000, 1999, 2000),
  cases = c(745, 2666, 37737, 80488, 212258, 213766),
  population = c(19987071, 20595360, 172006362, 174504898, 1272915272, 1280428583)
) # This is a tidy datasett
table1
```

**table 2**
```{r}
table2 <- tibble(
  country = c("Afghanistan", "Afghanistan","Afghanistan","Afghanistan", "Brazil", "Brazil", "Brazil", "Brazil", "China", "China","China", "China"),
year = c(1999,1999,2000, 2000,1999,1999,2000, 2000,1999,1999,2000, 2000),
type =  c("cases","population","cases","population", "cases","population","cases","population","cases","population","cases","population"),
count = c(745, 19987071, 2666,20595360,37737,172006362,80488,174504898,212258,1272915272,213766,1280428583)) # This data is the same but is messy
table2
```

**table 3**
```{r} 
table3 <- tibble(
  country = c("Afghanistan", "Afghanistan","Brazil", "Brazil", "China", "China"),
  year = c(1999,2000,1999,2000,1999,2000),
  rate= c(745/19987071,2666/20595360,37737/172006362,80488/174504898,212258/1272915272,213766/1280428583)
) # same with this one, it is messy
table3
```


```{r}
# Compute rate per 10,000
table1 %>% 
  mutate(rate = cases / population * 10000)

# Compute cases per year
table1 %>% 
  count(year, wt = cases)
```


```{r}
# Visualise changes over time
ggplot(table1, aes(year, cases)) + 
  geom_line(aes(group = country), colour = "grey50") + 
  geom_point(aes(colour = country))

```

# 2.3 Pivoting data to make it tidy

# 2.4 Lengthening datasets

```{r}
# We are using the data billboard as practise
billboard
```
**pivot longer**
```{r}
billboard %>% pivot_longer( # Pivot longer creates a long df of a wide one.
  cols = starts_with("wk"), # chooses the collums starting with wk
  names_to = "week", # puts the names from wk, into a collumn named week
  values_to = "rank", # adds the values to a coloumn named rank
  values_drop_na = TRUE
)
```


